name: Deploy to Packagist

on:
  release:
    types: [published]
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-packagist:
    runs-on: ubuntu-latest
    steps:
      - name: Update Packagist
        run: |
          curl -X POST -d "package=sbominator/cli" \
            "https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_TOKEN }}"
